2022-01-06 17:24:44,983 INFO    MainThread:410 [wandb_setup.py:_flush():71] setting env: {}
2022-01-06 17:24:44,984 INFO    MainThread:410 [wandb_setup.py:_flush():71] setting login settings: {}
2022-01-06 17:24:44,984 INFO    MainThread:410 [wandb_setup.py:_flush():71] setting login settings: {'api_key': '***REDACTED***'}
2022-01-06 17:24:44,985 INFO    MainThread:410 [wandb_init.py:_log_setup():371] Logging user logs to wandb/wandb/run-20220106_172444-e3cpeolt/logs/debug.log
2022-01-06 17:24:44,985 INFO    MainThread:410 [wandb_init.py:_log_setup():372] Logging internal logs to wandb/wandb/run-20220106_172444-e3cpeolt/logs/debug-internal.log
2022-01-06 17:24:44,986 INFO    MainThread:410 [wandb_init.py:init():404] calling init triggers
2022-01-06 17:24:44,986 INFO    MainThread:410 [wandb_init.py:init():411] wandb.init called with sweep_config: {}
config: {'resize': 0.25, 'batch_size': 8, 'viz_epoch': 10, 'learning_rate': 0.0001, 'num_epochs': 300, 'encoder_channels': [32, 32, 64, 64, 64], 'decoder_channels': [64, 64, 64, 32, 32], 'waypoints': [14, 29], 'temperature': 1.8, 'segmentation_model_fp': 'segmentation_models/SDD_segmentation.pth', 'semantic_classes': 6, 'loss_scale': 1000, 'kernlen': 31, 'nsig': 4, 'use_features_only': False, 'unfreeze': 100, 'use_TTST': True, 'rel_threshold': 0.002, 'use_CWS': True, 'CWS_params': {'sigma_factor': 6, 'ratio': 2, 'rot': True}}
2022-01-06 17:24:44,986 INFO    MainThread:410 [wandb_init.py:init():426] re-initializing run, found existing run on stack: 2xk6bljr
2022-01-06 17:24:44,989 INFO    MainThread:410 [wandb_run.py:finish():1457] finishing run pradipto611/ynet/2xk6bljr
2022-01-06 17:24:44,993 INFO    MainThread:410 [jupyter.py:save_history():429] not saving jupyter history
2022-01-06 17:24:44,993 INFO    MainThread:410 [jupyter.py:save_ipynb():374] not saving jupyter notebook
2022-01-06 17:24:44,994 INFO    MainThread:410 [wandb_init.py:_jupyter_teardown():303] cleaning up jupyter logic
2022-01-06 17:24:44,994 INFO    MainThread:410 [wandb_run.py:_atexit_cleanup():1780] got exitcode: 0
2022-01-06 17:24:44,997 INFO    MainThread:410 [wandb_run.py:_restore():1752] restore
2022-01-06 17:24:45,523 INFO    MainThread:410 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 671
  total_bytes: 671
}

2022-01-06 17:24:45,720 INFO    MainThread:410 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 671
  total_bytes: 671
}

2022-01-06 17:24:46,672 INFO    MainThread:410 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 3
}
pusher_stats {
  uploaded_bytes: 671
  total_bytes: 9268
}

2022-01-06 17:24:46,776 INFO    MainThread:410 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 671
  total_bytes: 16672
}

2022-01-06 17:24:46,880 INFO    MainThread:410 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 1953
  total_bytes: 16672
}

2022-01-06 17:24:46,984 INFO    MainThread:410 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 16672
  total_bytes: 16672
}

2022-01-06 17:24:47,087 INFO    MainThread:410 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 16672
  total_bytes: 16672
}

2022-01-06 17:24:47,189 INFO    MainThread:410 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 16672
  total_bytes: 16672
}

2022-01-06 17:24:47,291 INFO    MainThread:410 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 16672
  total_bytes: 16672
}

2022-01-06 17:24:47,393 INFO    MainThread:410 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 16672
  total_bytes: 16672
}

2022-01-06 17:24:48,578 INFO    MainThread:410 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 16672
  total_bytes: 16672
}

2022-01-06 17:24:48,933 INFO    MainThread:410 [wandb_run.py:_wait_for_finish():1912] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 16672
  total_bytes: 16672
}
local_info {
}

2022-01-06 17:24:50,430 INFO    MainThread:410 [wandb_run.py:_append_files():2180] logging synced files
2022-01-06 17:24:50,451 INFO    MainThread:410 [wandb_init.py:init():460] starting backend
2022-01-06 17:24:50,451 INFO    MainThread:410 [backend.py:_multiprocessing_setup():101] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2022-01-06 17:24:50,460 INFO    MainThread:410 [backend.py:ensure_launched():216] starting backend process...
2022-01-06 17:24:50,470 INFO    MainThread:410 [backend.py:ensure_launched():222] started backend process with pid: 675
2022-01-06 17:24:50,473 INFO    MainThread:410 [wandb_init.py:init():469] backend started and connected
2022-01-06 17:24:50,528 INFO    MainThread:410 [wandb_run.py:_label_probe_notebook():911] probe notebook
2022-01-06 17:24:51,920 INFO    MainThread:410 [wandb_init.py:init():533] updated telemetry
2022-01-06 17:24:51,928 INFO    MainThread:410 [wandb_init.py:init():563] communicating current version
2022-01-06 17:24:51,970 INFO    MainThread:410 [wandb_init.py:init():568] got version response 
2022-01-06 17:24:51,970 INFO    MainThread:410 [wandb_init.py:init():578] communicating run to backend with 30 second timeout
2022-01-06 17:24:52,167 INFO    MainThread:410 [wandb_init.py:init():606] starting run threads in backend
2022-01-06 17:24:54,961 INFO    MainThread:410 [wandb_run.py:_console_start():1810] atexit reg
2022-01-06 17:24:54,971 INFO    MainThread:410 [wandb_run.py:_redirect():1684] redirect: SettingsConsole.WRAP
2022-01-06 17:24:54,972 INFO    MainThread:410 [wandb_run.py:_redirect():1721] Wrapping output streams.
2022-01-06 17:24:54,974 INFO    MainThread:410 [wandb_run.py:_redirect():1745] Redirects installed.
2022-01-06 17:24:54,974 INFO    MainThread:410 [wandb_init.py:init():633] run started, returning control to user process
2022-01-06 17:24:54,975 INFO    MainThread:410 [wandb_watch.py:watch():43] Watching
2022-01-06 17:27:13,676 INFO    MainThread:410 [wandb_setup.py:_flush():71] setting env: {}
2022-01-06 17:27:13,677 INFO    MainThread:410 [wandb_setup.py:_flush():71] setting login settings: {}
2022-01-06 17:27:13,677 INFO    MainThread:410 [wandb_setup.py:_flush():71] setting login settings: {'api_key': '***REDACTED***'}
2022-01-06 17:27:13,678 INFO    MainThread:410 [wandb_init.py:_log_setup():371] Logging user logs to w_andb/wandb/run-20220106_172713-14dnmf4h/logs/debug.log
2022-01-06 17:27:13,679 INFO    MainThread:410 [wandb_init.py:_log_setup():372] Logging internal logs to w_andb/wandb/run-20220106_172713-14dnmf4h/logs/debug-internal.log
2022-01-06 17:27:13,679 INFO    MainThread:410 [wandb_init.py:_jupyter_setup():321] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x7f695c5a54d0>
2022-01-06 17:27:13,680 INFO    MainThread:410 [wandb_init.py:init():404] calling init triggers
2022-01-06 17:27:13,680 INFO    MainThread:410 [wandb_init.py:init():411] wandb.init called with sweep_config: {}
config: {'resize': 0.25, 'batch_size': 8, 'viz_epoch': 10, 'learning_rate': 0.0001, 'num_epochs': 300, 'encoder_channels': [32, 32, 64, 64, 64], 'decoder_channels': [64, 64, 64, 32, 32], 'waypoints': [14, 29], 'temperature': 1.8, 'segmentation_model_fp': 'segmentation_models/SDD_segmentation.pth', 'semantic_classes': 6, 'loss_scale': 1000, 'kernlen': 31, 'nsig': 4, 'use_features_only': False, 'unfreeze': 100, 'use_TTST': True, 'rel_threshold': 0.002, 'use_CWS': True, 'CWS_params': {'sigma_factor': 6, 'ratio': 2, 'rot': True}}
2022-01-06 17:27:13,681 INFO    MainThread:410 [wandb_init.py:init():426] re-initializing run, found existing run on stack: e3cpeolt
2022-01-06 17:27:13,683 INFO    MainThread:410 [wandb_run.py:finish():1457] finishing run pradipto611/ynet/e3cpeolt
2022-01-06 17:27:13,688 INFO    MainThread:410 [wandb_run.py:_atexit_cleanup():1780] got exitcode: 0
2022-01-06 17:27:13,691 INFO    MainThread:410 [wandb_run.py:_restore():1752] restore
2022-01-06 17:27:19,140 INFO    MainThread:410 [wandb_run.py:_wait_for_finish():1912] got exit ret: None
2022-01-06 17:27:19,241 INFO    MainThread:410 [wandb_run.py:_restore():1752] restore
2022-01-06 17:27:19,273 ERROR   MainThread:410 [wandb_init.py:init():958] error
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/wandb/sdk/wandb_run.py", line 1788, in _atexit_cleanup
    self._on_finish()
  File "/usr/local/lib/python3.7/dist-packages/wandb/sdk/wandb_run.py", line 1971, in _on_finish
    self._poll_exit_response = self._wait_for_finish()
  File "/usr/local/lib/python3.7/dist-packages/wandb/sdk/wandb_run.py", line 1911, in _wait_for_finish
    poll_exit_resp = self._backend.interface.communicate_poll_exit()
  File "/usr/local/lib/python3.7/dist-packages/wandb/sdk/interface/interface.py", line 586, in communicate_poll_exit
    resp = self._communicate_poll_exit(poll_exit)
  File "/usr/local/lib/python3.7/dist-packages/wandb/sdk/interface/interface_shared.py", line 402, in _communicate_poll_exit
    result = self._communicate(rec)
  File "/usr/local/lib/python3.7/dist-packages/wandb/sdk/interface/interface_shared.py", line 213, in _communicate
    return self._communicate_async(rec, local=local).get(timeout=timeout)
  File "/usr/local/lib/python3.7/dist-packages/wandb/sdk/interface/interface_shared.py", line 218, in _communicate_async
    raise Exception("The wandb backend process has shutdown")
Exception: The wandb backend process has shutdown

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/wandb/sdk/wandb_init.py", line 931, in init
    run = wi.init()
  File "/usr/local/lib/python3.7/dist-packages/wandb/sdk/wandb_init.py", line 437, in init
    self._wl._global_run_stack[-1].finish()
  File "/usr/local/lib/python3.7/dist-packages/wandb/sdk/wandb_run.py", line 1463, in finish
    self._atexit_cleanup(exit_code=exit_code)
  File "/usr/local/lib/python3.7/dist-packages/wandb/sdk/wandb_run.py", line 1797, in _atexit_cleanup
    self._backend.cleanup()
  File "/usr/local/lib/python3.7/dist-packages/wandb/sdk/backend/backend.py", line 245, in cleanup
    self.interface.join()
  File "/usr/local/lib/python3.7/dist-packages/wandb/sdk/interface/interface_shared.py", line 458, in join
    super().join()
  File "/usr/local/lib/python3.7/dist-packages/wandb/sdk/interface/interface.py", line 599, in join
    _ = self._communicate_shutdown()
  File "/usr/local/lib/python3.7/dist-packages/wandb/sdk/interface/interface_shared.py", line 455, in _communicate_shutdown
    _ = self._communicate(record)
  File "/usr/local/lib/python3.7/dist-packages/wandb/sdk/interface/interface_shared.py", line 213, in _communicate
    return self._communicate_async(rec, local=local).get(timeout=timeout)
  File "/usr/local/lib/python3.7/dist-packages/wandb/sdk/interface/interface_shared.py", line 218, in _communicate_async
    raise Exception("The wandb backend process has shutdown")
Exception: The wandb backend process has shutdown
2022-01-06 17:29:13,980 INFO    MainThread:410 [wandb_setup.py:_flush():71] setting env: {}
2022-01-06 17:29:13,981 INFO    MainThread:410 [wandb_setup.py:_flush():71] setting login settings: {}
2022-01-06 17:29:13,982 INFO    MainThread:410 [wandb_setup.py:_flush():71] setting login settings: {'api_key': '***REDACTED***'}
2022-01-06 17:29:13,983 INFO    MainThread:410 [wandb_init.py:_log_setup():371] Logging user logs to w_andb/wandb/run-20220106_172913-2fcyy5s7/logs/debug.log
2022-01-06 17:29:13,984 INFO    MainThread:410 [wandb_init.py:_log_setup():372] Logging internal logs to w_andb/wandb/run-20220106_172913-2fcyy5s7/logs/debug-internal.log
2022-01-06 17:29:13,984 INFO    MainThread:410 [wandb_init.py:init():404] calling init triggers
2022-01-06 17:29:13,985 INFO    MainThread:410 [wandb_init.py:init():411] wandb.init called with sweep_config: {}
config: {'resize': 0.25, 'batch_size': 8, 'viz_epoch': 10, 'learning_rate': 0.0001, 'num_epochs': 300, 'encoder_channels': [32, 32, 64, 64, 64], 'decoder_channels': [64, 64, 64, 32, 32], 'waypoints': [14, 29], 'temperature': 1.8, 'segmentation_model_fp': 'segmentation_models/SDD_segmentation.pth', 'semantic_classes': 6, 'loss_scale': 1000, 'kernlen': 31, 'nsig': 4, 'use_features_only': False, 'unfreeze': 100, 'use_TTST': True, 'rel_threshold': 0.002, 'use_CWS': True, 'CWS_params': {'sigma_factor': 6, 'ratio': 2, 'rot': True}}
2022-01-06 17:29:13,985 INFO    MainThread:410 [wandb_init.py:init():426] re-initializing run, found existing run on stack: e3cpeolt
2022-01-06 17:29:13,988 INFO    MainThread:410 [wandb_run.py:finish():1457] finishing run pradipto611/ynet/e3cpeolt
